
# Numpy

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

# What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

In [2]:
list=[2,3,4,5,7]

In [4]:
arr=np.array(list)

In [5]:
arr

array([2, 3, 4, 5, 7])

In [6]:
type(arr)

numpy.ndarray

In [7]:
# multinested array
my_list1=[1,2,3,4,5]
my_list2=[3,4,5,6,7]
my_list3=[5,6,7,8,9]

In [9]:
multi=np.array([my_list1,my_list2,my_list3])

In [10]:
multi

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [11]:
type(arr)

numpy.ndarray

In [13]:
multi.shape

(3, 5)

# Indexing

In [14]:
# accessing the array elements

In [15]:
arr

array([2, 3, 4, 5, 7])

In [16]:
arr[3]

5

In [17]:
multi

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [18]:
multi[1:,:2]

array([[3, 4],
       [5, 6]])

In [19]:
multi[:,3:]

array([[4, 5],
       [6, 7],
       [8, 9]])

In [20]:
arr[2:]=20

In [21]:
arr

array([ 2,  3, 20, 20, 20])

In [24]:
val=4
arr[arr<4]

array([2, 3])

In [25]:
# create array and reshape

In [27]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.arange(0,10).reshape(2,5)

In [29]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [33]:
np.ones((2,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [34]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
# random distribution

In [36]:
np.random.rand(3,3)

array([[ 0.97037832,  0.12207928,  0.77425161],
       [ 0.27118334,  0.35731826,  0.73421012],
       [ 0.10985281,  0.2060271 ,  0.76837912]])

In [46]:
rand=np.random.randn(4,4)

In [47]:
rand

array([[-1.25465828, -0.65886228,  0.21603668, -0.84691569],
       [ 1.37050722, -0.10451171, -1.08544407,  0.14843706],
       [-0.0825981 , -1.72034989, -1.00200886,  0.58095449],
       [-0.54140512, -1.34574702, -1.00772444, -1.03279253]])

In [48]:
import seaborn as sns

In [49]:
import pandas as pd

In [50]:
sns.distplot(pd.DataFrame(rand.reshape(16,1)))

C:\Users\Nayeemuddin\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "


In [51]:
np.random.randint(0,100,8).reshape(4,2)

array([[91, 74],
       [59, 26],
       [94, 66],
       [46, 60]])

In [54]:
np.random.random_sample((1,5))

array([[ 0.88762815,  0.36597821,  0.80686193,  0.64074114,  0.29046725]])